baseURL = "https://bruhtus.github.io/"
languageCode = "en-us"
title = "bruhtus >/dev/null"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true

[markup.goldmark.renderer]
    unsafe = true

# ref: https://discourse.gohugo.io/t/syntax-highlighting-how-do-i-change-the-theme/30323
# ref: https://xyproto.github.io/splash/docs/all.html
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = 'native'
    tabWidth = 2

[params]
    author = "Robertus Chris"
    favicon = "favicon.ico"
    custom_css = ["/css/custom.css"]
    custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    indentifier = "about"
    name = "About"
    pre = "<i class='fa fa-user fa-lg'></i>"
    url = "/About/"
    weight = 10

[[menu.main]]
    indentifier = "posts"
    name = "Posts"
    pre = "<i class='fa fa-mug-hot fa-lg'></i>"
    url = "/posts/"
    weight = 30

[[menu.main]]
    indentifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:diawan@pm.me"
    weight = 40

[[menu.tab]]
    indentifier = "github"
    name = "Github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/bruhtus"
    weight = 50
